version: 2
registries:
  self-loop:
    type: npm-registry
    url: "http://127.0.0.1:1080"
    token: "${{secrets.REG_TOKEN}}"
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    registries:
      - "self-loop"