name: Deployment Reactor
on:
  deployment_status:
jobs:
  react-prod:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: |
          echo "PRODUCTION REACTOR TRIGGERED"
          echo "Creator: ${{ github.event.deployment.creator.login }}"
          echo "Prod secret present: $([ ${#PROD_SECRET} -gt 0 ] && echo YES || echo NO)"
          echo "Prod secret length: ${#PROD_SECRET}"
        env:
          PROD_SECRET: ${{ secrets.PROD_SECRET }}
