name: OIDC Reusable Caller
on:
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
jobs:
  call_reusable:
    permissions:
      contents: read
      id-token: write
    uses: tooforg/private-test-repo/.github/workflows/reusable-callee.yml@main
