name: test 660

on:
  issues:
    types: [opened]

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  call:
    permissions:
      contents: read
      id-token: write
      attestations: write
    uses: tooforg/invisible-repo/.github/workflows/test-621.yml@main
    with:
      value: test value ${{ github.event.issue.number }}
