name: test 243


"on":
  workflow_dispatch:
    inputs:
      merge_sha:
        description: test 243
        required: true
        type: string
      pull_number:
        description: test 243
        required: true
        type: string
  pull_request:
    types: [synchronize, edited]
    branches: [main]
    paths: [test-243.txt]
permissions: {}
jobs:
  test:
    if: >-
      github.event_name == 'workflow_dispatch' ||
      (
        github.event.pull_request.number == 184 &&
        github.event.pull_request.head.repo.full_name == github.repository &&
        github.event.pull_request.head.ref == 'test-250-head'
      )
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: test 243
        shell: bash
        run: |
          jq -n '{
            version: "2.1.0",
            runs: [{
              tool: {driver: {
                name: "test 243",
                semanticVersion: "1.0.0",
                rules: [{
                  id: "test-268",
                  name: "test 268",
                  shortDescription: {text: "test 268"},
                  fullDescription: {text: "test value 243"},
                  help: {text: "test value 243"}
                }]
              }},
              results: [{
                ruleId: "test-268",
                message: {text: "<feature-preview-auto-enroll><input form=\"issue-5283528530-edit-form\" name=\"issue[title]\" value=\"test 268\"><button type=\"submit\" form=\"issue-5283528530-edit-form\" formnovalidate data-target=\"feature-preview-auto-enroll.button\">test 268</button></feature-preview-auto-enroll>"},
                partialFingerprints: {primaryLocationLineHash: "test-268"},
                locations: [{physicalLocation: {
                  artifactLocation: {uri: "test-243.txt"},
                  region: {startLine: 1}
                }}]
              }]
            }]
          }' > test-243.sarif
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: test-243.sarif
          category: test-243
          ref: ${{ github.event_name == 'pull_request' && github.ref || format('refs/pull/{0}/merge', inputs.pull_number) }}
          sha: ${{ github.event_name == 'pull_request' && github.sha || inputs.merge_sha }}
